[package]
name = "dev_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.2.16"
sha1 = "0.10.0"
base64 = "0.13.0"
notify = "4.0.17"
regex = "1.5"
